image: docker:latest
services:
  - docker:dind

stages:
  - build_develop
  - build_feature

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker info | grep Registry

build_develop:
  stage: build_develop
  script:
    - echo Build started on `date` for $CI_COMMIT_REF_NAME
    - docker build -t $CI_REGISTRY_IMAGE:develop .
    - docker images
    - docker push $CI_REGISTRY_IMAGE:develop
  only:
    - develop

build_feature:
  stage: build_feature
  script:
    - echo Build started on `date` for $CI_COMMIT_REF_NAME
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker images
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - /^feature.*$/
