image: docker:latest
services:
  - docker:dind

stages:
  - build_latest
  - build_tags
  - build_skeleton_opss
  - build_skeleton_l2wgs

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker info | grep Registry

build_latest:
  stage: build_latest
  script:
    - echo Build started on `date` for $CI_COMMIT_REF_NAME
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - cd /skeletons/open-publishing-space-site && docker build -t $CI_REGISTRY_IMAGE:skeleton-open-publishing-space-v1.5.5
    - cd /skeletons/learn2-with-git-sync && docker build -t $CI_REGISTRY_IMAGE:skeleton-learn2-with-git-sync-v1.5.2
    - docker images
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:skeleton-open-publishing-space-v1.5.5
    - docker push $CI_REGISTRY_IMAGE:skeleton-learn2-with-git-sync-v1.5.2
  only:
    - master

build_tags:
  stage: build_tags
  script: 
    - echo Build started on `date` for $CI_COMMIT_TAG
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - /^v[0-9.]+$/