image: docker:latest
services:
  - docker:dind

stages:
  - build_latest
  - build_skeleton_opss
  - build_skeleton_l2wgs

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker info | grep Registry

build_latest:
  stage: build_latest
  script:
    - echo Build started on `date` for $CI_COMMIT_REF_NAME
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker images
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

build_skeleton_opss:
  stage: build_skeleton_opss
  script:
    - echo Build started on `date` for $CI_COMMIT_TAG
    - cd skeletons/open-publishing-space-site && docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker images
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - /^skeleton-open-publishing-space-.*$/

build_skeleton_l2wgs:
  stage: build_skeleton_l2wgs
  script:
    - echo Build started on `date` for $CI_COMMIT_TAG
    - cd skeletons/learn2-with-git-sync && docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker images
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - /^skeleton-learn2-with-git-sync-.*$/